version: "3.8"

services:
  localstack:
    image: localstack/localstack:3.8.1
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - REGION=us-east-1
    volumes:
      - ./scripts/localstack.sh:/etc/localstack/init/ready.d/localstack.sh
